"""Refactor participants to use user_id and role_id

Revision ID: 1e5df79a93a5
Revises: b1f050ecef40
Create Date: 2025-11-15 12:05:52.193396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5df79a93a5'
down_revision: Union[str, Sequence[str], None] = 'b1f050ecef40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
