"""Update participant + role models

Revision ID: 386fb22986d9
Revises: 6e4bdbe7bcb4
Create Date: 2025-11-16 11:49:18.802824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386fb22986d9'
down_revision: Union[str, Sequence[str], None] = '6e4bdbe7bcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('slots_required', sa.Integer(), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('roles', 'slots_required')
    # ### end Alembic commands ###
