"""Refactor participants to use user_id and role_id

Revision ID: 6396db7a4e71
Revises: 1e5df79a93a5
Create Date: 2025-11-15 12:22:03.764782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6396db7a4e71'
down_revision: Union[str, Sequence[str], None] = '1e5df79a93a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('participants', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'participants', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('participants', 'contact_info')
    op.drop_column('participants', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('participants', sa.Column('contact_info', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'role_id')
    op.drop_column('participants', 'user_id')
    # ### end Alembic commands ###
