"""initial clean migration

Revision ID: 65387d80fba7
Revises: 
Create Date: 2025-11-16 18:08:16.121750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65387d80fba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('repeat_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('slots_available', sa.Integer(), nullable=True))
    op.drop_column('events', 'event_date')
    op.drop_column('events', 'recurrence_pattern')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('recurrence_pattern', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('events', 'slots_available')
    op.drop_table('recurrences')
    # ### end Alembic commands ###
