"""Update roles/participants structure

Revision ID: b1f050ecef40
Revises: 7dde7080a86a
Create Date: 2025-11-15 12:01:19.840993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f050ecef40'
down_revision: Union[str, Sequence[str], None] = '7dde7080a86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('roles', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('assigned_to', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('roles', 'updated_at')
    # ### end Alembic commands ###
