"""attendance final

Revision ID: bf7f4b4102b2
Revises: 1e180e8859df
Create Date: 2025-11-19 10:59:41.988102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf7f4b4102b2'
down_revision: Union[str, Sequence[str], None] = '1e180e8859df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('attendance_day', sa.Date(), nullable=False))
    op.add_column('attendances', sa.Column('marked_by', sa.UUID(), nullable=True))
    op.add_column('attendances', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('attendances', 'attended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_attendances_attendance_day'), 'attendances', ['attendance_day'], unique=False)
    op.create_foreign_key(None, 'attendances', 'users', ['marked_by'], ['id'])
    op.drop_column('attendances', 'note')
    op.drop_column('attendances', 'created_at')
    op.drop_column('attendances', 'present')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('present', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_index(op.f('ix_attendances_attendance_day'), table_name='attendances')
    op.alter_column('attendances', 'attended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('attendances', 'notes')
    op.drop_column('attendances', 'marked_by')
    op.drop_column('attendances', 'attendance_day')
    # ### end Alembic commands ###
